### ISSUE TITLE
Miner running in background at https://iota.codebuffet.co/ ?

### ISSUE THREAD

**Issue by pRizz** [peterwilli/IOTA-tangle-explorer#6]
Your demo site at https://iota.codebuffet.co/ is taking 80% CPU with no indication or opt in. Please don't do this as it jeopardizes your user base. At least make it an opt-in.

**Comment by peterwilli** [comment]
Sorry about that, it was a demo. I wanted to see how it worked. I thought I removed it, will remove it right now :)
